<html>
<head>
<meta http-equiv="Content-Language" content="en" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Berkeley Frozen Pizza Delivered</title>
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#FF9966" vlink="#FF9966" alink="#FFCC99">
<table width=100%>
  <tr>
    <td>
      <img src="http://www.salesforce.com/us/assets/developer/adn_logo.gif" alt="" border="0">
      <H2> Berkeley Frozen Pizza - Frozen Pizza Delivered</H2>
    </td>
    <td>
      <img src="veggie_pizza.jpg" alt="" border="0">
    </td>
  </tr>
  <tr>
    <td colspan=2>
      <hr>
    </td>
  </tr>
  <tr>
    <td>
      <a href="index.php">Home</a> |
      <a href="pizza.php">Pizza of the Day</a> |
      <a href="selfserviceportal.php">Self-Service Portal</a> |
      <a href="logout.php">Log Out</a>
    </td>
    <td align=right>
      <a href="signup.php">Sign Up</a>
    </td>
  </tr>
</table>

<hr>