<?php


/**
 * Admin settings form with credentials.
 *//*
function salesforce_ssp_auth_settings_form() {
	$form['sfdc_ssp_username'] = array(
		'#type'				=> 'textfield',
		'#title' 			=> t('Self-Service Username'),
		'#size'				=> 30,
		'#max_length'		=> 128,
		'#default_value'	=> variable_get('sfdc_ssp_username',''),
	);
	$form['sfdc_ssp_password'] = array(
		'#type'				=> 'textfield',
		'#title' 			=> t('Self-Service Password'),
		'#size'				=> 30,
		'#max_length'		=> 128,
		'#default_value'	=> variable_get('sfdc_ssp_password',''),
	);
	$form['sfdc_ssp_api_key'] = array(
		'#type'				=> 'textfield',
		'#title' 			=> t('Self-Service Security Key'),
		'#size'				=> 30,
		'#max_length'		=> 128,
		'#default_value'	=> variable_get('sfdc_ssp_api_key',''),
	);
	$form['sfdc_ssp_wsdl_path'] = array(
		'#type'				=> 'textfield',
		'#title' 			=> t('Self-Service WSDL Path'),
		'#size'				=> 30,
		'#max_length'		=> 128,
		'#default_value'	=> variable_get('sfdc_ssp_wsdl_path',''),
		'#description'		=> 'Absolute path to partner WSDL.',
	);
	return system_settings_form($form);
}*/